channels:
  - name: "ChannelName1"
    webhook: "WebHookURL1"
  - name: "ChannelName2"
    webhook: "WebHookURL2"

# %s = PlayerUUID
avatarURL: "https://crafatar.com/avatars/%s?size=512&overlay=helm"

errorText: "/notice [ChannelName] [Message]"
resultText: |-
  Sent to Discord
  %s